-- Postgres migration 0005 (2026-09-25, Phase 6: processes, fairness, budgets, org settings, raw
-- payloads). Hand-written; the SQLite side is store/migrate.py migration 9 and the tracked files
-- store/schema-sales.sql, which tests/test_schema_parity.py checks a database migrated through here against.
--
--   wf_events.priority  claimed highest first (10 interactive requests, 0 imports, -10 history backfills)
--   wf_events.owner     whose work the event is (orchestrator/bus.owner_for); the claim takes a per-owner
--                       advisory lock for the duration of handling, so one owner has one running event
--   org_settings        the settings overlay (what user_dir()/<name>.yaml is locally), versioned
--   raw_payloads        OWNED: what a recorder, an upload or a paste delivered, before interpretation
--
-- Numbering: 0003 is Phase 2 (row-level security) and 0004 is Phase 3 (Google sign-in); they were written
-- in parallel with this file. raw_payloads is an OWNED table created AFTER 0003, so the merge that brings
-- 0003 in must also give raw_payloads its FORCE ROW LEVEL SECURITY and owner policy (a follow-up numbered
-- file, or this one if 0003 lands first): tests/isolation's live lint will say so.

-- ---- the bus: priority and owner --------------------------------------------------------------
ALTER TABLE wf_events ADD COLUMN priority INTEGER NOT NULL DEFAULT 0;
ALTER TABLE wf_events ADD COLUMN owner TEXT;
CREATE INDEX idx_wf_claim ON wf_events(status, priority, id);

-- ---- org settings ---------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS org_settings (
  name       TEXT PRIMARY KEY,
  body       TEXT NOT NULL DEFAULT '{}',
  version    INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT,
  updated_by TEXT
);

-- ---- raw payloads (OWNED) --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_payloads (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id    TEXT NOT NULL DEFAULT NULLIF(current_setting('app.user_id', true), ''),
  source_kind TEXT NOT NULL,
  source_ref  TEXT,
  encoding    TEXT NOT NULL DEFAULT 'text' CHECK(encoding IN ('text','json','base64')),
  body        TEXT NOT NULL,
  sha256      TEXT NOT NULL,
  created_at  TEXT NOT NULL,
  UNIQUE(owner_id, sha256)
);
CREATE INDEX idx_raw_payloads_owner_id ON raw_payloads(owner_id);
