-- Postgres migration 0007 (2026-09-25, Phase 7: the manager product). Hand-written; the SQLite side is
-- store/migrate.py migration 11 and the tracked store/schema-sales.sql, which tests/test_schema_parity.py
-- checks a database migrated through here against. (0006 is Phase 4's recorder step.)
--
--   comments     OWNED by the rep whose call / deal / email / loop it is on (or, for a coaching note,
--                the rep it is about); author_id is who wrote it: the rep, or a manager of the rep's
--                team. The one OWNED table a non-owner inserts into; the reason is in store/rls.py.
--   access_log   SYSTEM, insert-only: who opened someone else's call or deal page, and when.
--
-- Row-level security for both is in the repeatable store/pg/rls.sql, applied after every numbered step
-- (store/pgmigrate.py). owner_id defaults to the session setting like every OWNED table, but the app
-- always names it: the owner of a comment is the owner of the commented object, never the author.

CREATE TABLE IF NOT EXISTS comments (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id    TEXT NOT NULL DEFAULT NULLIF(current_setting('app.user_id', true), ''),
  author_id   TEXT NOT NULL,
  entity_type TEXT NOT NULL CHECK(entity_type IN ('call','deal','email','loop','coaching')),
  entity_id   TEXT NOT NULL,
  turn_idx    INTEGER,
  body        TEXT NOT NULL,
  created_at  TEXT NOT NULL,
  resolved_at TEXT,
  resolved_by TEXT
);
CREATE INDEX idx_comments_owner_id ON comments(owner_id);
CREATE INDEX idx_comments_entity ON comments(entity_type, entity_id);

CREATE TABLE IF NOT EXISTS access_log (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  viewer_id     TEXT NOT NULL,
  owner_user_id TEXT NOT NULL,
  entity_type   TEXT NOT NULL CHECK(entity_type IN ('call','deal')),
  entity_id     TEXT NOT NULL,
  viewed_at     TEXT NOT NULL
);
CREATE INDEX idx_access_log_entity ON access_log(entity_type, entity_id, viewed_at);
