-- Postgres migration 0010 (2026-09-27, serverless deployment). Hand-written; the SQLite side is
-- store/migrate.py migration 14 and the tail of store/schema-sales.sql, which tests/test_schema_parity.py
-- checks a database migrated through here against.
--
--   auth_pending    a sign-in or consent attempt between the redirect to Google and the callback
--                   (googleauth.StorePending): state (as sha256), nonce, PKCE verifier, one use, ten minutes
--   auth_attempts   the sign-in rate limits (hosted.StoreLimiter): one row per counted attempt, per limit
--
-- Both used to live in the web process's memory, which holds only while there is exactly one web process. On a
-- serverless platform (Vercel) consecutive requests reach different instances, and a Render web service may be
-- scaled out too. SYSTEM tables; their row-level policies are in the repeatable store/pg/rls.sql.

CREATE TABLE IF NOT EXISTS auth_pending (
  state_hash TEXT PRIMARY KEY,
  client     TEXT,
  created    DOUBLE PRECISION NOT NULL,
  data       TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_auth_pending_client ON auth_pending(client, created);
CREATE INDEX IF NOT EXISTS idx_auth_pending_created ON auth_pending(created);

CREATE TABLE IF NOT EXISTS auth_attempts (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket TEXT NOT NULL,
  key    TEXT NOT NULL,
  at     DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_auth_attempts_key ON auth_attempts(bucket, key, at);
