-- GENERATED by scripts/gen_pg_rls.py from store/tenancy.py. Do not edit: change the classification
-- and regenerate (tests/isolation/test_rls_generated.py fails when this file and the generator differ).
-- Postgres REPEATABLE step (store/pgmigrate.py): row-level security. Applied after every numbered
-- migration whenever this file's sha256 differs from the one in schema_repeatables, in one transaction,
-- so it must stay idempotent: every policy in the schema is dropped first and re-created below.
-- Session settings: app.user_id and app.mode ('interactive' | 'service'), set by store/db.py
-- PostgresConnection.bind_actor / _on_begin. Roles: the OWNER role applies this file (it must have
-- BYPASSRLS, see docs/architecture.md "Isolation"); the APP role salescoach_app is what the running app
-- connects as and is subject to every policy below. Policy summary per class: store/rls.py.

-- ---- start clean: every policy on every table of this schema -------------------------------------
-- The policy set below is complete; anything a previous version of this file created and this one does not
-- (a removed or renamed policy) must not survive.
DO $$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname, tablename FROM pg_policies WHERE schemaname = current_schema() LOOP
    EXECUTE format('DROP POLICY %I ON %I.%I', p.policyname, current_schema(), p.tablename);
  END LOOP;
END $$;

-- ---- the app role: privileges on this schema, never a bypass ----------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'salescoach_app') THEN
    RAISE EXCEPTION 'role salescoach_app does not exist: CREATE ROLE salescoach_app LOGIN PASSWORD ''...'' NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE (docs/architecture.md, "Isolation")';
  END IF;
  IF (SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = 'salescoach_app') THEN
    RAISE EXCEPTION 'role salescoach_app must be neither a superuser nor BYPASSRLS';
  END IF;
  EXECUTE format('GRANT USAGE ON SCHEMA %I TO salescoach_app', current_schema());
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO salescoach_app', current_schema());
  EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO salescoach_app', current_schema());
  EXECUTE format('REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON %I.schema_migrations FROM salescoach_app', current_schema());
  EXECUTE format('REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON %I.schema_repeatables FROM salescoach_app', current_schema());
  EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA %I GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO salescoach_app', current_user, current_schema());
  EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA %I GRANT USAGE, SELECT ON SEQUENCES TO salescoach_app', current_user, current_schema());
END $$;

-- ---- who is acting ------------------------------------------------------------------------------
-- The acting user's id; NULL when nothing bound one (fails closed everywhere below).
CREATE OR REPLACE FUNCTION app_actor_id() RETURNS text LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.user_id', true), '')
$$;

-- A mode is bound. Writes need one; 'interactive' is a person at the keyboard, 'service' a background duty.
CREATE OR REPLACE FUNCTION app_mode_ok() RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT current_setting('app.mode', true) IN ('interactive', 'service')
$$;

-- The acting user exists and is active (SECURITY DEFINER: reads users as the owner, so the users policies
-- cannot recurse into themselves).
CREATE OR REPLACE FUNCTION app_actor_active() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT EXISTS (SELECT 1 FROM users WHERE id = app_actor_id() AND status = 'active')
$$;

-- The acting user's role when active, else NULL (a disabled admin is nobody).
CREATE OR REPLACE FUNCTION app_actor_role() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT role FROM users WHERE id = app_actor_id() AND status = 'active'
$$;

-- The owners whose rows the acting user may read: themselves, plus (interactive sessions only) every member of
-- every team they manage. Empty for nobody, for an unknown or inactive user, and for an admin who manages no
-- team. A service session (a duty, the worker) reads its own rows only.
CREATE OR REPLACE FUNCTION app_visible_owners() RETURNS text[] LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT COALESCE(
    (SELECT ARRAY[me.id] || ARRAY(
       SELECT u.id FROM team_managers tm JOIN users u ON u.team_id = tm.team_id
       WHERE tm.user_id = me.id AND u.id <> me.id
         AND current_setting('app.mode', true) = 'interactive')
     FROM users me WHERE me.id = app_actor_id() AND me.status = 'active'),
    '{}'::text[])
$$;

-- The acting user may write a row owned by `owner`: it is their own, they are active, a mode is bound.
CREATE OR REPLACE FUNCTION app_can_write(owner text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT owner IS NOT NULL AND owner = app_actor_id() AND app_mode_ok() AND app_actor_active()
$$;

-- No user exists yet: the first users row (the local user, the bootstrap admin) may be inserted by anyone.
CREATE OR REPLACE FUNCTION app_users_empty() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT NOT EXISTS (SELECT 1 FROM users)
$$;

-- Whose node this is, readable with nobody bound: the worker resolves an event's owner before it can bind
-- that owner (orchestrator/workflow.owner_of_event). An id, never content; needs the owner role to BYPASSRLS.
CREATE OR REPLACE FUNCTION app_owner_of(node text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT owner_id FROM nodes WHERE id = node
$$;

-- Whose recorder connection this is (Phase 4), readable with nobody bound: the push webhook
-- (/import/webhook/{connection_id}, sources/connections.py) learns the owner before it can bind them, and
-- the owner is the ONLY identity an import through it can take (the payload never names one). NULL for an
-- unknown or disconnected connection and for an owner who is not active. An id, never content.
CREATE OR REPLACE FUNCTION app_source_connection_owner(connection text) RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT c.owner_id FROM source_connections c JOIN users u ON u.id = c.owner_id
  WHERE c.id = connection AND c.status <> 'disconnected' AND u.status = 'active'
$$;

-- Model spend since `since` (budget.py, Phase 6), numbers only. The org's daily cap must count every rep's
-- runs, which no rep may read; the Usage panel under Settings (admin-only in cloud mode) lists spend per
-- user. Both answer only to an active user; per owner, an admin gets every owner and anyone else the owners
-- they may read (app_visible_owners). A sum per owner, never a row of agent_runs.
CREATE OR REPLACE FUNCTION app_org_spend_since(since text) RETURNS double precision
LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT CASE WHEN app_actor_active() THEN COALESCE(SUM(cost_usd), 0)::double precision ELSE 0 END
  FROM agent_runs WHERE started_at >= since
$$;

CREATE OR REPLACE FUNCTION app_spend_by_owner_since(since text)
RETURNS TABLE(owner_id text, spent double precision, runs bigint, unpriced bigint, deferred bigint)
LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT r.owner_id, COALESCE(SUM(r.cost_usd), 0)::double precision, COUNT(*),
         SUM(CASE WHEN r.cost_usd IS NULL AND r.status = 'ok' THEN 1 ELSE 0 END),
         SUM(CASE WHEN r.error LIKE 'budget_deferred:%' THEN 1 ELSE 0 END)
  FROM agent_runs r
  WHERE r.started_at >= since AND app_actor_active()
    AND (app_actor_role() = 'admin' OR r.owner_id = ANY (app_visible_owners()))
  GROUP BY r.owner_id ORDER BY r.owner_id
$$;

-- The child-owner trigger (0002) reads the parent row; as the app role it would see nothing of another user's
-- parent and let a mismatched child through. As the owner it sees every parent and refuses the mismatch.
ALTER FUNCTION app_child_owner() SECURITY DEFINER;

-- A user may edit their own profile; only an admin changes who someone is in the org. The one status change a
-- user makes themselves is accepting their own invite at their first Google sign-in (invited -> active,
-- web/auth.py _resolve_user); every other status change is an admin's. The guard constrains the APP role
-- (session_user: current_user is the definer in here); the owner role, an operator at psql or the migrator,
-- bypasses row security altogether and is not the app.
CREATE OR REPLACE FUNCTION app_users_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF session_user = 'salescoach_app' AND app_actor_role() IS DISTINCT FROM 'admin' AND (
       NEW.id IS DISTINCT FROM OLD.id OR NEW.role IS DISTINCT FROM OLD.role
       OR NEW.team_id IS DISTINCT FROM OLD.team_id
       OR (NEW.status IS DISTINCT FROM OLD.status
           AND NOT (OLD.status = 'invited' AND NEW.status = 'active' AND OLD.id = app_actor_id()))) THEN
    RAISE EXCEPTION 'only an admin may change a user''s id, role, team or status'
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_users_guard ON users;
CREATE TRIGGER trg_users_guard BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION app_users_guard();

-- Whose object an (entity_type, entity_id) names (Phase 7: comments and access_log), readable by the policies
-- whoever asks: a call, deal or loop node's owner, an email's owner, or, for a coaching note, the user it is
-- about. An owner id, never content (like app_owner_of); NULL for anything that does not exist.
-- (Parameters are prefixed: nodes has a column named `kind`, which would shadow a parameter of that name.)
CREATE OR REPLACE FUNCTION app_entity_owner(p_type text, p_id text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT CASE
    WHEN p_type IN ('call', 'deal', 'loop') THEN (SELECT n.owner_id FROM nodes n WHERE n.id = p_id AND n.type = p_type)
    WHEN p_type = 'email' THEN (SELECT e.owner_id FROM emails e
                                WHERE e.id = CASE WHEN p_id ~ '^[0-9]{1,9}$' THEN p_id::integer END)
    WHEN p_type = 'coaching' THEN (SELECT u.id FROM users u WHERE u.id = p_id)
  END
$$;

-- A comment's thread, author and time never change; only its author edits the text; a resolve is signed by
-- whoever resolved it. The policies say WHO may update a comment (its rep or its author); this says WHAT.
CREATE OR REPLACE FUNCTION app_comments_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF session_user = 'salescoach_app' AND (
       NEW.id IS DISTINCT FROM OLD.id OR NEW.owner_id IS DISTINCT FROM OLD.owner_id
       OR NEW.author_id IS DISTINCT FROM OLD.author_id OR NEW.entity_type IS DISTINCT FROM OLD.entity_type
       OR NEW.entity_id IS DISTINCT FROM OLD.entity_id OR NEW.turn_idx IS DISTINCT FROM OLD.turn_idx
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR (NEW.body IS DISTINCT FROM OLD.body AND OLD.author_id IS DISTINCT FROM app_actor_id())
       OR (NEW.resolved_by IS DISTINCT FROM OLD.resolved_by AND NEW.resolved_by IS DISTINCT FROM app_actor_id()
           AND NEW.resolved_by IS NOT NULL)) THEN
    RAISE EXCEPTION 'a comment keeps its thread, author and time; only its author edits it; a resolve is signed by who resolved it'
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_comments_guard ON comments;
CREATE TRIGGER trg_comments_guard BEFORE UPDATE ON comments FOR EACH ROW EXECUTE FUNCTION app_comments_guard();

-- ---- OWNED: one rep's work; the owner writes, the owner's managers read --------------------------------
-- agent_runs: OWNED
ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY agent_runs_select ON agent_runs FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY agent_runs_insert ON agent_runs FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY agent_runs_update ON agent_runs FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY agent_runs_delete ON agent_runs FOR DELETE USING (app_can_write(owner_id));
-- artifacts: OWNED
ALTER TABLE artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE artifacts FORCE ROW LEVEL SECURITY;
CREATE POLICY artifacts_select ON artifacts FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY artifacts_insert ON artifacts FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY artifacts_update ON artifacts FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY artifacts_delete ON artifacts FOR DELETE USING (app_can_write(owner_id));
-- assessments: OWNED
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessments FORCE ROW LEVEL SECURITY;
CREATE POLICY assessments_select ON assessments FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY assessments_insert ON assessments FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY assessments_update ON assessments FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY assessments_delete ON assessments FOR DELETE USING (app_can_write(owner_id));
-- autosend_log: OWNED
ALTER TABLE autosend_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE autosend_log FORCE ROW LEVEL SECURITY;
CREATE POLICY autosend_log_select ON autosend_log FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY autosend_log_insert ON autosend_log FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY autosend_log_update ON autosend_log FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY autosend_log_delete ON autosend_log FOR DELETE USING (app_can_write(owner_id));
-- calendar_cache: OWNED
ALTER TABLE calendar_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_cache FORCE ROW LEVEL SECURITY;
CREATE POLICY calendar_cache_select ON calendar_cache FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY calendar_cache_insert ON calendar_cache FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY calendar_cache_update ON calendar_cache FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY calendar_cache_delete ON calendar_cache FOR DELETE USING (app_can_write(owner_id));
-- calendar_meetings: OWNED
ALTER TABLE calendar_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_meetings FORCE ROW LEVEL SECURITY;
CREATE POLICY calendar_meetings_select ON calendar_meetings FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY calendar_meetings_insert ON calendar_meetings FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY calendar_meetings_update ON calendar_meetings FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY calendar_meetings_delete ON calendar_meetings FOR DELETE USING (app_can_write(owner_id));
-- call_participants: OWNED
ALTER TABLE call_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE call_participants FORCE ROW LEVEL SECURITY;
CREATE POLICY call_participants_select ON call_participants FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY call_participants_insert ON call_participants FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY call_participants_update ON call_participants FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY call_participants_delete ON call_participants FOR DELETE USING (app_can_write(owner_id));
-- calls: OWNED
ALTER TABLE calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE calls FORCE ROW LEVEL SECURITY;
CREATE POLICY calls_select ON calls FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY calls_insert ON calls FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY calls_update ON calls FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY calls_delete ON calls FOR DELETE USING (app_can_write(owner_id));
-- claims: OWNED
ALTER TABLE claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE claims FORCE ROW LEVEL SECURITY;
CREATE POLICY claims_select ON claims FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY claims_insert ON claims FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY claims_update ON claims FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY claims_delete ON claims FOR DELETE USING (app_can_write(owner_id));
-- coach_reports: OWNED
ALTER TABLE coach_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE coach_reports FORCE ROW LEVEL SECURITY;
CREATE POLICY coach_reports_select ON coach_reports FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY coach_reports_insert ON coach_reports FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY coach_reports_update ON coach_reports FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY coach_reports_delete ON coach_reports FOR DELETE USING (app_can_write(owner_id));
-- coach_state: OWNED
ALTER TABLE coach_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE coach_state FORCE ROW LEVEL SECURITY;
CREATE POLICY coach_state_select ON coach_state FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY coach_state_insert ON coach_state FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY coach_state_update ON coach_state FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY coach_state_delete ON coach_state FOR DELETE USING (app_can_write(owner_id));
-- comments: OWNED
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments FORCE ROW LEVEL SECURITY;
CREATE POLICY comments_select ON comments FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY comments_insert ON comments FOR INSERT WITH CHECK (author_id = app_actor_id() AND app_mode_ok() AND owner_id = ANY (app_visible_owners()) AND owner_id = app_entity_owner(entity_type, entity_id) AND (entity_type <> 'coaching' OR owner_id <> author_id));
CREATE POLICY comments_update ON comments FOR UPDATE USING (app_can_write(owner_id) OR (author_id = app_actor_id() AND app_mode_ok() AND owner_id = ANY (app_visible_owners()))) WITH CHECK (app_can_write(owner_id) OR (author_id = app_actor_id() AND app_mode_ok() AND owner_id = ANY (app_visible_owners())));
CREATE POLICY comments_delete ON comments FOR DELETE USING (author_id = app_actor_id() AND app_mode_ok() AND owner_id = ANY (app_visible_owners()));
-- deal_health: OWNED
ALTER TABLE deal_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal_health FORCE ROW LEVEL SECURITY;
CREATE POLICY deal_health_select ON deal_health FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY deal_health_insert ON deal_health FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_health_update ON deal_health FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_health_delete ON deal_health FOR DELETE USING (app_can_write(owner_id));
-- deal_health_history: OWNED
ALTER TABLE deal_health_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal_health_history FORCE ROW LEVEL SECURITY;
CREATE POLICY deal_health_history_select ON deal_health_history FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY deal_health_history_insert ON deal_health_history FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_health_history_update ON deal_health_history FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_health_history_delete ON deal_health_history FOR DELETE USING (app_can_write(owner_id));
-- deal_people: OWNED
ALTER TABLE deal_people ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal_people FORCE ROW LEVEL SECURITY;
CREATE POLICY deal_people_select ON deal_people FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY deal_people_insert ON deal_people FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_people_update ON deal_people FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_people_delete ON deal_people FOR DELETE USING (app_can_write(owner_id));
-- deal_risks: OWNED
ALTER TABLE deal_risks ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal_risks FORCE ROW LEVEL SECURITY;
CREATE POLICY deal_risks_select ON deal_risks FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY deal_risks_insert ON deal_risks FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_risks_update ON deal_risks FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_risks_delete ON deal_risks FOR DELETE USING (app_can_write(owner_id));
-- deal_stage_history: OWNED
ALTER TABLE deal_stage_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal_stage_history FORCE ROW LEVEL SECURITY;
CREATE POLICY deal_stage_history_select ON deal_stage_history FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY deal_stage_history_insert ON deal_stage_history FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_stage_history_update ON deal_stage_history FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY deal_stage_history_delete ON deal_stage_history FOR DELETE USING (app_can_write(owner_id));
-- deals: OWNED
ALTER TABLE deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE deals FORCE ROW LEVEL SECURITY;
CREATE POLICY deals_select ON deals FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY deals_insert ON deals FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY deals_update ON deals FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY deals_delete ON deals FOR DELETE USING (app_can_write(owner_id));
-- derived_outcomes: OWNED
ALTER TABLE derived_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE derived_outcomes FORCE ROW LEVEL SECURITY;
CREATE POLICY derived_outcomes_select ON derived_outcomes FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY derived_outcomes_insert ON derived_outcomes FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY derived_outcomes_update ON derived_outcomes FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY derived_outcomes_delete ON derived_outcomes FOR DELETE USING (app_can_write(owner_id));
-- edges: OWNED
ALTER TABLE edges ENABLE ROW LEVEL SECURITY;
ALTER TABLE edges FORCE ROW LEVEL SECURITY;
CREATE POLICY edges_select ON edges FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY edges_insert ON edges FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY edges_update ON edges FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY edges_delete ON edges FOR DELETE USING (app_can_write(owner_id));
-- email_edits: OWNED
ALTER TABLE email_edits ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_edits FORCE ROW LEVEL SECURITY;
CREATE POLICY email_edits_select ON email_edits FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY email_edits_insert ON email_edits FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY email_edits_update ON email_edits FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY email_edits_delete ON email_edits FOR DELETE USING (app_can_write(owner_id));
-- email_replies: OWNED
ALTER TABLE email_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_replies FORCE ROW LEVEL SECURITY;
CREATE POLICY email_replies_select ON email_replies FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY email_replies_insert ON email_replies FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY email_replies_update ON email_replies FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY email_replies_delete ON email_replies FOR DELETE USING (app_can_write(owner_id));
-- emails: OWNED
ALTER TABLE emails ENABLE ROW LEVEL SECURITY;
ALTER TABLE emails FORCE ROW LEVEL SECURITY;
CREATE POLICY emails_select ON emails FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY emails_insert ON emails FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY emails_update ON emails FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY emails_delete ON emails FOR DELETE USING (app_can_write(owner_id));
-- embeddings: OWNED
ALTER TABLE embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE embeddings FORCE ROW LEVEL SECURITY;
CREATE POLICY embeddings_select ON embeddings FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY embeddings_insert ON embeddings FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY embeddings_update ON embeddings FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY embeddings_delete ON embeddings FOR DELETE USING (app_can_write(owner_id));
-- events: OWNED
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE events FORCE ROW LEVEL SECURITY;
CREATE POLICY events_select ON events FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY events_insert ON events FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY events_update ON events FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY events_delete ON events FOR DELETE USING (app_can_write(owner_id));
-- field_provenance: OWNED
ALTER TABLE field_provenance ENABLE ROW LEVEL SECURITY;
ALTER TABLE field_provenance FORCE ROW LEVEL SECURITY;
CREATE POLICY field_provenance_select ON field_provenance FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY field_provenance_insert ON field_provenance FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY field_provenance_update ON field_provenance FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY field_provenance_delete ON field_provenance FOR DELETE USING (app_can_write(owner_id));
-- followup_decisions: OWNED
ALTER TABLE followup_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE followup_decisions FORCE ROW LEVEL SECURITY;
CREATE POLICY followup_decisions_select ON followup_decisions FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY followup_decisions_insert ON followup_decisions FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY followup_decisions_update ON followup_decisions FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY followup_decisions_delete ON followup_decisions FOR DELETE USING (app_can_write(owner_id));
-- learned_patterns: OWNED
ALTER TABLE learned_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE learned_patterns FORCE ROW LEVEL SECURITY;
CREATE POLICY learned_patterns_select ON learned_patterns FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY learned_patterns_insert ON learned_patterns FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY learned_patterns_update ON learned_patterns FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY learned_patterns_delete ON learned_patterns FOR DELETE USING (app_can_write(owner_id));
-- learning_proposals: OWNED
ALTER TABLE learning_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_proposals FORCE ROW LEVEL SECURITY;
CREATE POLICY learning_proposals_select ON learning_proposals FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY learning_proposals_insert ON learning_proposals FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY learning_proposals_update ON learning_proposals FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY learning_proposals_delete ON learning_proposals FOR DELETE USING (app_can_write(owner_id));
-- loops: OWNED
ALTER TABLE loops ENABLE ROW LEVEL SECURITY;
ALTER TABLE loops FORCE ROW LEVEL SECURITY;
CREATE POLICY loops_select ON loops FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY loops_insert ON loops FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY loops_update ON loops FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY loops_delete ON loops FOR DELETE USING (app_can_write(owner_id));
-- meddpicc: OWNED
ALTER TABLE meddpicc ENABLE ROW LEVEL SECURITY;
ALTER TABLE meddpicc FORCE ROW LEVEL SECURITY;
CREATE POLICY meddpicc_select ON meddpicc FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY meddpicc_insert ON meddpicc FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY meddpicc_update ON meddpicc FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY meddpicc_delete ON meddpicc FOR DELETE USING (app_can_write(owner_id));
-- memory_conflicts: OWNED
ALTER TABLE memory_conflicts ENABLE ROW LEVEL SECURITY;
ALTER TABLE memory_conflicts FORCE ROW LEVEL SECURITY;
CREATE POLICY memory_conflicts_select ON memory_conflicts FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY memory_conflicts_insert ON memory_conflicts FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY memory_conflicts_update ON memory_conflicts FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY memory_conflicts_delete ON memory_conflicts FOR DELETE USING (app_can_write(owner_id));
-- nodes: OWNED
ALTER TABLE nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE nodes FORCE ROW LEVEL SECURITY;
CREATE POLICY nodes_select ON nodes FOR SELECT USING ((owner_id IS NULL AND app_actor_active()) OR owner_id = ANY (app_visible_owners()));
CREATE POLICY nodes_insert ON nodes FOR INSERT WITH CHECK ((owner_id IS NULL AND app_actor_active() AND app_mode_ok()) OR app_can_write(owner_id));
CREATE POLICY nodes_update ON nodes FOR UPDATE USING ((owner_id IS NULL AND app_actor_active() AND app_mode_ok()) OR app_can_write(owner_id)) WITH CHECK ((owner_id IS NULL AND app_actor_active() AND app_mode_ok()) OR app_can_write(owner_id));
CREATE POLICY nodes_delete ON nodes FOR DELETE USING ((owner_id IS NULL AND app_actor_active() AND app_mode_ok()) OR app_can_write(owner_id));
-- nudges: OWNED
ALTER TABLE nudges ENABLE ROW LEVEL SECURITY;
ALTER TABLE nudges FORCE ROW LEVEL SECURITY;
CREATE POLICY nudges_select ON nudges FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY nudges_insert ON nudges FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY nudges_update ON nudges FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY nudges_delete ON nudges FOR DELETE USING (app_can_write(owner_id));
-- pattern_observations: OWNED
ALTER TABLE pattern_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE pattern_observations FORCE ROW LEVEL SECURITY;
CREATE POLICY pattern_observations_select ON pattern_observations FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY pattern_observations_insert ON pattern_observations FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY pattern_observations_update ON pattern_observations FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY pattern_observations_delete ON pattern_observations FOR DELETE USING (app_can_write(owner_id));
-- prep_briefs: OWNED
ALTER TABLE prep_briefs ENABLE ROW LEVEL SECURITY;
ALTER TABLE prep_briefs FORCE ROW LEVEL SECURITY;
CREATE POLICY prep_briefs_select ON prep_briefs FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY prep_briefs_insert ON prep_briefs FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY prep_briefs_update ON prep_briefs FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY prep_briefs_delete ON prep_briefs FOR DELETE USING (app_can_write(owner_id));
-- raw_payloads: OWNED
ALTER TABLE raw_payloads ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_payloads FORCE ROW LEVEL SECURITY;
CREATE POLICY raw_payloads_select ON raw_payloads FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY raw_payloads_insert ON raw_payloads FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY raw_payloads_update ON raw_payloads FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY raw_payloads_delete ON raw_payloads FOR DELETE USING (app_can_write(owner_id));
-- reconciliations: OWNED
ALTER TABLE reconciliations ENABLE ROW LEVEL SECURITY;
ALTER TABLE reconciliations FORCE ROW LEVEL SECURITY;
CREATE POLICY reconciliations_select ON reconciliations FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY reconciliations_insert ON reconciliations FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY reconciliations_update ON reconciliations FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY reconciliations_delete ON reconciliations FOR DELETE USING (app_can_write(owner_id));
-- reply_proposals: OWNED
ALTER TABLE reply_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE reply_proposals FORCE ROW LEVEL SECURITY;
CREATE POLICY reply_proposals_select ON reply_proposals FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY reply_proposals_insert ON reply_proposals FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY reply_proposals_update ON reply_proposals FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY reply_proposals_delete ON reply_proposals FOR DELETE USING (app_can_write(owner_id));
-- seller_observations: OWNED
ALTER TABLE seller_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE seller_observations FORCE ROW LEVEL SECURITY;
CREATE POLICY seller_observations_select ON seller_observations FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY seller_observations_insert ON seller_observations FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY seller_observations_update ON seller_observations FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY seller_observations_delete ON seller_observations FOR DELETE USING (app_can_write(owner_id));
-- seller_patterns: OWNED
ALTER TABLE seller_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE seller_patterns FORCE ROW LEVEL SECURITY;
CREATE POLICY seller_patterns_select ON seller_patterns FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY seller_patterns_insert ON seller_patterns FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY seller_patterns_update ON seller_patterns FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY seller_patterns_delete ON seller_patterns FOR DELETE USING (app_can_write(owner_id));
-- slot_fills: OWNED
ALTER TABLE slot_fills ENABLE ROW LEVEL SECURITY;
ALTER TABLE slot_fills FORCE ROW LEVEL SECURITY;
CREATE POLICY slot_fills_select ON slot_fills FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY slot_fills_insert ON slot_fills FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY slot_fills_update ON slot_fills FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY slot_fills_delete ON slot_fills FOR DELETE USING (app_can_write(owner_id));
-- source_connections: OWNED
ALTER TABLE source_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_connections FORCE ROW LEVEL SECURITY;
CREATE POLICY source_connections_select ON source_connections FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY source_connections_insert ON source_connections FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY source_connections_update ON source_connections FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY source_connections_delete ON source_connections FOR DELETE USING (app_can_write(owner_id));
-- sources: OWNED
ALTER TABLE sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE sources FORCE ROW LEVEL SECURITY;
CREATE POLICY sources_select ON sources FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY sources_insert ON sources FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY sources_update ON sources FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY sources_delete ON sources FOR DELETE USING (app_can_write(owner_id));
-- speakers: OWNED
ALTER TABLE speakers ENABLE ROW LEVEL SECURITY;
ALTER TABLE speakers FORCE ROW LEVEL SECURITY;
CREATE POLICY speakers_select ON speakers FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY speakers_insert ON speakers FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY speakers_update ON speakers FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY speakers_delete ON speakers FOR DELETE USING (app_can_write(owner_id));
-- stakeholders: OWNED
ALTER TABLE stakeholders ENABLE ROW LEVEL SECURITY;
ALTER TABLE stakeholders FORCE ROW LEVEL SECURITY;
CREATE POLICY stakeholders_select ON stakeholders FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY stakeholders_insert ON stakeholders FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY stakeholders_update ON stakeholders FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY stakeholders_delete ON stakeholders FOR DELETE USING (app_can_write(owner_id));
-- turns: OWNED
ALTER TABLE turns ENABLE ROW LEVEL SECURITY;
ALTER TABLE turns FORCE ROW LEVEL SECURITY;
CREATE POLICY turns_select ON turns FOR SELECT USING (owner_id = ANY (app_visible_owners()));
CREATE POLICY turns_insert ON turns FOR INSERT WITH CHECK (app_can_write(owner_id));
CREATE POLICY turns_update ON turns FOR UPDATE USING (app_can_write(owner_id)) WITH CHECK (app_can_write(owner_id));
CREATE POLICY turns_delete ON turns FOR DELETE USING (app_can_write(owner_id));

-- ---- ORG: the shared directory -------------------------------------------------------------------------
-- accounts: ORG
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounts NO FORCE ROW LEVEL SECURITY;
CREATE POLICY accounts_select ON accounts FOR SELECT USING (app_actor_active());
CREATE POLICY accounts_insert ON accounts FOR INSERT WITH CHECK (app_actor_active() AND app_mode_ok());
CREATE POLICY accounts_update ON accounts FOR UPDATE USING (app_actor_active() AND app_mode_ok()) WITH CHECK (app_actor_active() AND app_mode_ok());
CREATE POLICY accounts_delete ON accounts FOR DELETE USING (app_actor_active() AND app_mode_ok());
-- people: ORG
ALTER TABLE people ENABLE ROW LEVEL SECURITY;
ALTER TABLE people NO FORCE ROW LEVEL SECURITY;
CREATE POLICY people_select ON people FOR SELECT USING (app_actor_active());
CREATE POLICY people_insert ON people FOR INSERT WITH CHECK (app_actor_active() AND app_mode_ok());
CREATE POLICY people_update ON people FOR UPDATE USING (app_actor_active() AND app_mode_ok()) WITH CHECK (app_actor_active() AND app_mode_ok());
CREATE POLICY people_delete ON people FOR DELETE USING (app_actor_active() AND app_mode_ok());
-- team_managers: ORG
ALTER TABLE team_managers ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_managers NO FORCE ROW LEVEL SECURITY;
CREATE POLICY team_managers_select ON team_managers FOR SELECT USING (true);
CREATE POLICY team_managers_insert ON team_managers FOR INSERT WITH CHECK (app_actor_role() = 'admin');
CREATE POLICY team_managers_update ON team_managers FOR UPDATE USING (app_actor_role() = 'admin') WITH CHECK (app_actor_role() = 'admin');
CREATE POLICY team_managers_delete ON team_managers FOR DELETE USING (app_actor_role() = 'admin');
-- teams: ORG
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams NO FORCE ROW LEVEL SECURITY;
CREATE POLICY teams_select ON teams FOR SELECT USING (true);
CREATE POLICY teams_insert ON teams FOR INSERT WITH CHECK (app_actor_role() = 'admin');
CREATE POLICY teams_update ON teams FOR UPDATE USING (app_actor_role() = 'admin') WITH CHECK (app_actor_role() = 'admin');
CREATE POLICY teams_delete ON teams FOR DELETE USING (app_actor_role() = 'admin');
-- users: ORG
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users NO FORCE ROW LEVEL SECURITY;
CREATE POLICY users_select ON users FOR SELECT USING (true);
CREATE POLICY users_insert ON users FOR INSERT WITH CHECK (app_actor_role() = 'admin' OR app_users_empty());
CREATE POLICY users_update ON users FOR UPDATE USING (app_actor_role() = 'admin' OR id = app_actor_id()) WITH CHECK (app_actor_role() = 'admin' OR id = app_actor_id());
CREATE POLICY users_delete ON users FOR DELETE USING (app_actor_role() = 'admin');

-- ---- SYSTEM: the machinery -----------------------------------------------------------------------------
-- access_log: SYSTEM
ALTER TABLE access_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE access_log NO FORCE ROW LEVEL SECURITY;
CREATE POLICY access_log_select ON access_log FOR SELECT USING (owner_user_id = ANY (app_visible_owners()));
CREATE POLICY access_log_insert ON access_log FOR INSERT WITH CHECK (viewer_id = app_actor_id() AND app_mode_ok() AND owner_user_id = ANY (app_visible_owners()) AND owner_user_id = app_entity_owner(entity_type, entity_id));
-- invites: SYSTEM
ALTER TABLE invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE invites NO FORCE ROW LEVEL SECURITY;
CREATE POLICY invites_select ON invites FOR SELECT USING (true);
CREATE POLICY invites_insert ON invites FOR INSERT WITH CHECK (app_actor_role() = 'admin');
CREATE POLICY invites_update ON invites FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY invites_delete ON invites FOR DELETE USING (app_actor_role() = 'admin');
-- oauth_tokens: SYSTEM
ALTER TABLE oauth_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_tokens NO FORCE ROW LEVEL SECURITY;
CREATE POLICY oauth_tokens_select ON oauth_tokens FOR SELECT USING ((user_id = app_actor_id() AND app_actor_active()) OR app_actor_role() = 'admin');
CREATE POLICY oauth_tokens_insert ON oauth_tokens FOR INSERT WITH CHECK ((user_id = app_actor_id() AND app_actor_active()) OR app_actor_role() = 'admin');
CREATE POLICY oauth_tokens_update ON oauth_tokens FOR UPDATE USING ((user_id = app_actor_id() AND app_actor_active()) OR app_actor_role() = 'admin') WITH CHECK ((user_id = app_actor_id() AND app_actor_active()) OR app_actor_role() = 'admin');
CREATE POLICY oauth_tokens_delete ON oauth_tokens FOR DELETE USING ((user_id = app_actor_id() AND app_actor_active()) OR app_actor_role() = 'admin');
-- org_settings: SYSTEM
ALTER TABLE org_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_settings NO FORCE ROW LEVEL SECURITY;
CREATE POLICY org_settings_select ON org_settings FOR SELECT USING (true);
CREATE POLICY org_settings_insert ON org_settings FOR INSERT WITH CHECK (app_actor_active() AND app_mode_ok() AND app_actor_role() = 'admin');
CREATE POLICY org_settings_update ON org_settings FOR UPDATE USING (app_actor_active() AND app_mode_ok() AND app_actor_role() = 'admin') WITH CHECK (app_actor_active() AND app_mode_ok() AND app_actor_role() = 'admin');
CREATE POLICY org_settings_delete ON org_settings FOR DELETE USING (app_actor_active() AND app_mode_ok() AND app_actor_role() = 'admin');
-- schema_migrations: SYSTEM
ALTER TABLE schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE schema_migrations NO FORCE ROW LEVEL SECURITY;
CREATE POLICY schema_migrations_select ON schema_migrations FOR SELECT USING (true);
-- schema_repeatables: SYSTEM
ALTER TABLE schema_repeatables ENABLE ROW LEVEL SECURITY;
ALTER TABLE schema_repeatables NO FORCE ROW LEVEL SECURITY;
CREATE POLICY schema_repeatables_select ON schema_repeatables FOR SELECT USING (true);
-- sessions: SYSTEM
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions NO FORCE ROW LEVEL SECURITY;
CREATE POLICY sessions_select ON sessions FOR SELECT USING (true);
CREATE POLICY sessions_insert ON sessions FOR INSERT WITH CHECK (true);
CREATE POLICY sessions_update ON sessions FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY sessions_delete ON sessions FOR DELETE USING (true);
-- state: SYSTEM
ALTER TABLE state ENABLE ROW LEVEL SECURITY;
ALTER TABLE state NO FORCE ROW LEVEL SECURITY;
CREATE POLICY state_select ON state FOR SELECT USING (app_actor_active() OR key LIKE 'ops:%');
CREATE POLICY state_insert ON state FOR INSERT WITH CHECK (app_actor_active() AND app_mode_ok() AND (app_actor_role() = 'admin' OR current_setting('app.mode', true) = 'service') OR key LIKE 'ops:%');
CREATE POLICY state_update ON state FOR UPDATE USING (app_actor_active() AND app_mode_ok() AND (app_actor_role() = 'admin' OR current_setting('app.mode', true) = 'service') OR key LIKE 'ops:%') WITH CHECK (app_actor_active() AND app_mode_ok() AND (app_actor_role() = 'admin' OR current_setting('app.mode', true) = 'service') OR key LIKE 'ops:%');
CREATE POLICY state_delete ON state FOR DELETE USING (app_actor_active() AND app_mode_ok() AND (app_actor_role() = 'admin' OR current_setting('app.mode', true) = 'service'));
-- user_speaker_labels: SYSTEM
ALTER TABLE user_speaker_labels ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_speaker_labels NO FORCE ROW LEVEL SECURITY;
CREATE POLICY user_speaker_labels_select ON user_speaker_labels FOR SELECT USING (user_id = app_actor_id() AND app_actor_active());
CREATE POLICY user_speaker_labels_insert ON user_speaker_labels FOR INSERT WITH CHECK (user_id = app_actor_id() AND app_actor_active());
CREATE POLICY user_speaker_labels_update ON user_speaker_labels FOR UPDATE USING (user_id = app_actor_id() AND app_actor_active()) WITH CHECK (user_id = app_actor_id() AND app_actor_active());
CREATE POLICY user_speaker_labels_delete ON user_speaker_labels FOR DELETE USING (user_id = app_actor_id() AND app_actor_active());
-- user_state: SYSTEM
ALTER TABLE user_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_state NO FORCE ROW LEVEL SECURITY;
CREATE POLICY user_state_select ON user_state FOR SELECT USING (user_id = app_actor_id() AND app_actor_active());
CREATE POLICY user_state_insert ON user_state FOR INSERT WITH CHECK (user_id = app_actor_id() AND app_actor_active());
CREATE POLICY user_state_update ON user_state FOR UPDATE USING (user_id = app_actor_id() AND app_actor_active()) WITH CHECK (user_id = app_actor_id() AND app_actor_active());
CREATE POLICY user_state_delete ON user_state FOR DELETE USING (user_id = app_actor_id() AND app_actor_active());
-- wf_events: SYSTEM
ALTER TABLE wf_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE wf_events NO FORCE ROW LEVEL SECURITY;
CREATE POLICY wf_events_select ON wf_events FOR SELECT USING (true);
CREATE POLICY wf_events_insert ON wf_events FOR INSERT WITH CHECK (true);
CREATE POLICY wf_events_update ON wf_events FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY wf_events_delete ON wf_events FOR DELETE USING (true);
