"""The two schemas are the same schema.

store/pg/0001_baseline.sql is generated from the SQLite files; this pins (1) that the committed
file is what the generator produces today and (2), on Postgres, that a live database built from
it has the same tables, the same columns in the same order, the same NOT NULL, the same primary
and unique keys, the same indexes (by columns, partial ones included), the same defaults and the
same number of CHECK constraints as the SQLite schema. Any drift fails here, on either side.
"""
import importlib.util
import re
import sys
from pathlib import Path

import pytest

from salescoach.store import catalog, tenancy

ROOT = Path(__file__).resolve().parent.parent


def _generator():
    spec = importlib.util.spec_from_file_location("gen_pg_baseline", ROOT / "scripts" / "gen_pg_baseline.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("gen_pg_baseline", mod)
    spec.loader.exec_module(mod)
    return mod


def test_committed_baseline_matches_the_generator():
    gen = _generator()
    assert gen.OUT.read_text() == gen.generate(), "run scripts/gen_pg_baseline.py and commit the result"


def test_generator_rewrites_only_types_and_pragmas():
    gen = _generator()
    src = "PRAGMA foreign_keys = ON;\nCREATE TABLE IF NOT EXISTS t (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n" \
          "  x REAL DEFAULT 0.5,\n  b BLOB NOT NULL,\n  \"by\" TEXT NOT NULL,\n  n INTEGER NOT NULL DEFAULT 0 CHECK(n IN (0,1))\n);\n"
    out = gen.convert(src)
    assert "PRAGMA" not in out
    assert "  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," in out
    assert "  x DOUBLE PRECISION DEFAULT 0.5," in out and "  b BYTEA NOT NULL," in out
    assert '  "by" TEXT NOT NULL,' in out and "  n INTEGER NOT NULL DEFAULT 0 CHECK(n IN (0,1))" in out


def _norm_default(value):
    if value is None:
        return None
    value = str(value)
    value = re.sub(r"::[a-z ]+$", "", value)          # '[]'::text -> '[]'
    if re.fullmatch(r"-?\d+\.0", value):
        value = value[:-2] + ".0"
    return value


@pytest.mark.postgres_only
def test_live_postgres_schema_matches_sqlite(db):
    pg_tables = {r[0] for r in db.execute(
        "SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema() "
        "AND table_type = 'BASE TABLE'")}
    lite_tables = set(catalog.tables())
    assert pg_tables - set(tenancy.POSTGRES_ONLY) == lite_tables - set(tenancy.SQLITE_ONLY)

    drift = []
    for table, cols in catalog.tables().items():
        pg_cols = db.execute("PRAGMA table_info(%s)" % table).fetchall()
        if [c.name for c in cols] != [r["name"] for r in pg_cols]:
            drift.append(f"{table}: columns {[c.name for c in cols]} != {[r['name'] for r in pg_cols]}")
            continue
        for c, r in zip(cols, pg_cols):
            if (c.notnull or bool(c.pk)) != bool(r["notnull"]):
                drift.append(f"{table}.{c.name}: NOT NULL sqlite={c.notnull or bool(c.pk)} postgres={bool(r['notnull'])}")
            if c.pk != r["pk"]:
                drift.append(f"{table}.{c.name}: pk position sqlite={c.pk} postgres={r['pk']}")
            pg_default = None if (r["dflt_value"] or "").startswith("nextval(") else r["dflt_value"]
            if _norm_default(c.default) != _norm_default(pg_default) and not (c.pk and table in catalog.identity_tables()):
                drift.append(f"{table}.{c.name}: default sqlite={c.default!r} postgres={pg_default!r}")

    # indexes and unique keys, compared by (unique, columns), plus which ones are partial
    pg_idx = db.execute(
        "SELECT i.indexrelid::regclass::text AS name, t.relname AS tbl, i.indisunique, i.indisprimary, "
        "pg_get_expr(i.indpred, i.indrelid) AS pred, "
        "ARRAY(SELECT a.attname FROM unnest(i.indkey) WITH ORDINALITY k(attnum, ord) "
        "      JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = k.attnum ORDER BY k.ord) AS cols "
        "FROM pg_index i JOIN pg_class t ON t.oid = i.indrelid JOIN pg_namespace n ON n.oid = t.relnamespace "
        "WHERE n.nspname = current_schema()").fetchall()
    for table in catalog.tables():
        want = {(ix.unique, ix.columns, bool(ix.where)) for ix in catalog.indexes() if ix.table == table}
        # SQLite's INTEGER PRIMARY KEY is the rowid and has no index of its own; Postgres backs the same key
        # with a unique index. Every other primary key is an index on both sides.
        have = {(bool(r["indisunique"]), tuple(r["cols"]), r["pred"] is not None) for r in pg_idx
                if r["tbl"] == table and not (r["indisprimary"] and table in catalog.identity_tables())}
        if want != have:
            drift.append(f"{table}: indexes sqlite={sorted(want)} postgres={sorted(have)}")

    # CHECK constraints: the same number per table (their text differs only in quoting)
    pg_checks = {}
    for r in db.execute(
            "SELECT t.relname, COUNT(*) FROM pg_constraint c JOIN pg_class t ON t.oid = c.conrelid "
            "JOIN pg_namespace n ON n.oid = t.relnamespace WHERE n.nspname = current_schema() AND c.contype = 'c' "
            "GROUP BY t.relname"):
        pg_checks[r[0]] = r[1]
    for table, n in catalog.check_counts().items():
        if pg_checks.get(table, 0) != n:
            drift.append(f"{table}: CHECK constraints sqlite={n} postgres={pg_checks.get(table, 0)}")

    assert not drift, "\n".join(drift)
