"""Row-level security, generated from the table classification in tenancy.py.

store/pg/0003_rls.sql is `generate()` written to disk (scripts/gen_pg_rls.py); tests/isolation/
test_rls_generated.py fails when the file and the generator disagree, so the SQL and the
classification cannot drift: a table that changes class is re-policied by regenerating, and a
table nobody classified never gets to Postgres (tests/isolation/test_catalog_lint.py).

The contract (docs/architecture.md, "Isolation"):

  * Two session settings, and only two: app.user_id (the acting user's id, '' for nobody) and
    app.mode ('interactive' | 'service'). PostgresConnection.bind_actor sets them for the session
    and _on_begin re-issues them transaction-locally at the start of EVERY transaction.
  * Two roles. The OWNER role runs migrations (it owns every table and the SECURITY DEFINER
    functions; it has BYPASSRLS, so a migration sees every row) and is never used at runtime. The
    APP role (`salescoach_app`: no superuser, no BYPASSRLS, no CREATE) is what DATABASE_URL names;
    every table has row-level security ENABLED for it, and every OWNED table has it FORCED so that
    not even the owner's own statements skip the policies unless the role bypasses RLS outright.
  * app_visible_owners(): the acting user's id plus the ids of every member of the teams the user
    manages (team_managers + users.team_id). It reads the directory live, so demoting a manager
    takes effect on the next query. A user whose row is missing or not `active` sees nothing;
    an admin who manages no team sees no content.

Policies, per class:

  OWNED   SELECT   owner_id = ANY(app_visible_owners())        (nodes: a NULL owner_id, the org
                   directory's account and person nodes, is readable by any active user)
          INSERT / UPDATE / DELETE   app_can_write(owner_id): the row is the acting user's own,
                   the user is active and a mode is bound. A manager reads a rep's rows and can
                   never write one; nobody bound reads and writes nothing.
  ORG     accounts, people: readable and writable by any active user (every rep contributes to
                   the shared directory). users, teams, team_managers: readable by every connection
                   (a connection has to read `users` to learn who it is); writable by admins, and
                   a user may update their own users row except id, role, team_id and status
                   (trg_users_guard); the first user of an empty directory may be inserted by
                   anyone (the bootstrap).
  SYSTEM  wf_events: open to every connection of the app role (the bus carries ids and step names,
                   never content; the web layer publishes from interactive requests, the worker
                   claims with no user bound). state: readable by any active user, written by
                   admins and service-mode duties. user_state and user_speaker_labels: the acting
                   user's own rows. schema_migrations: readable; the app role has no write privilege.

The SECURITY DEFINER helpers read users / team_managers / nodes as the owner role, which is why
those tables are ENABLED but not FORCED (a policy that reads its own table would recurse) and why
the owner role must bypass RLS for app_owner_of() (the worker learns an event's owner before it can
bind that owner; the function returns an owner id, never content).
"""
from pathlib import Path

from . import tenancy

APP_ROLE = "salescoach_app"
OUT = Path(__file__).with_name("pg") / "0003_rls.sql"

HEADER = f"""-- GENERATED by scripts/gen_pg_rls.py from store/tenancy.py. Do not edit: change the classification
-- and regenerate (tests/isolation/test_rls_generated.py fails when this file and the generator differ).
-- Postgres migration 0003 (2026-09-25): row-level security. Session settings: app.user_id and
-- app.mode ('interactive' | 'service'), set by store/db.py PostgresConnection.bind_actor / _on_begin.
-- Roles: the OWNER role applies this file (it must have BYPASSRLS, see docs/architecture.md
-- "Isolation"); the APP role {APP_ROLE} is what the running app connects as and is subject to
-- every policy below. Policy summary per class: store/rls.py.

"""

ROLE_BOOTSTRAP = f"""-- ---- the app role: privileges on this schema, never a bypass ----------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
    RAISE EXCEPTION 'role {APP_ROLE} does not exist: CREATE ROLE {APP_ROLE} LOGIN PASSWORD ''...'' NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE (docs/architecture.md, "Isolation")';
  END IF;
  IF (SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
    RAISE EXCEPTION 'role {APP_ROLE} must be neither a superuser nor BYPASSRLS';
  END IF;
  EXECUTE format('GRANT USAGE ON SCHEMA %I TO {APP_ROLE}', current_schema());
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO {APP_ROLE}', current_schema());
  EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO {APP_ROLE}', current_schema());
  EXECUTE format('REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON %I.schema_migrations FROM {APP_ROLE}', current_schema());
  EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA %I GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {APP_ROLE}', current_user, current_schema());
  EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA %I GRANT USAGE, SELECT ON SEQUENCES TO {APP_ROLE}', current_user, current_schema());
END $$;

"""

FUNCTIONS = """-- ---- who is acting ------------------------------------------------------------------------------
-- The acting user's id; NULL when nothing bound one (fails closed everywhere below).
CREATE OR REPLACE FUNCTION app_actor_id() RETURNS text LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.user_id', true), '')
$$;

-- A mode is bound. Writes need one; 'interactive' is a person at the keyboard, 'service' a background duty.
CREATE OR REPLACE FUNCTION app_mode_ok() RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT current_setting('app.mode', true) IN ('interactive', 'service')
$$;

-- The acting user exists and is active (SECURITY DEFINER: reads users as the owner, so the users policies
-- cannot recurse into themselves).
CREATE OR REPLACE FUNCTION app_actor_active() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT EXISTS (SELECT 1 FROM users WHERE id = app_actor_id() AND status = 'active')
$$;

-- The acting user's role when active, else NULL (a disabled admin is nobody).
CREATE OR REPLACE FUNCTION app_actor_role() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT role FROM users WHERE id = app_actor_id() AND status = 'active'
$$;

-- The owners whose rows the acting user may read: themselves, plus every member of every team they manage.
-- Empty for nobody, for an unknown or inactive user, and for an admin who manages no team.
CREATE OR REPLACE FUNCTION app_visible_owners() RETURNS text[] LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT COALESCE(
    (SELECT ARRAY[me.id] || ARRAY(
       SELECT u.id FROM team_managers tm JOIN users u ON u.team_id = tm.team_id
       WHERE tm.user_id = me.id AND u.id <> me.id)
     FROM users me WHERE me.id = app_actor_id() AND me.status = 'active'),
    '{}'::text[])
$$;

-- The acting user may write a row owned by `owner`: it is their own, they are active, a mode is bound.
CREATE OR REPLACE FUNCTION app_can_write(owner text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT owner IS NOT NULL AND owner = app_actor_id() AND app_mode_ok() AND app_actor_active()
$$;

-- No user exists yet: the first users row (the local user, the bootstrap admin) may be inserted by anyone.
CREATE OR REPLACE FUNCTION app_users_empty() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT NOT EXISTS (SELECT 1 FROM users)
$$;

-- Whose node this is, readable with nobody bound: the worker resolves an event's owner before it can bind
-- that owner (orchestrator/workflow.owner_of_event). An id, never content; needs the owner role to BYPASSRLS.
CREATE OR REPLACE FUNCTION app_owner_of(node text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT owner_id FROM nodes WHERE id = node
$$;

-- The child-owner trigger (0002) reads the parent row; as the app role it would see nothing of another user's
-- parent and let a mismatched child through. As the owner it sees every parent and refuses the mismatch.
ALTER FUNCTION app_child_owner() SECURITY DEFINER;

-- A user may edit their own profile; only an admin changes who someone is in the org.
CREATE OR REPLACE FUNCTION app_users_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF app_actor_role() IS DISTINCT FROM 'admin' AND (
       NEW.id IS DISTINCT FROM OLD.id OR NEW.role IS DISTINCT FROM OLD.role
       OR NEW.team_id IS DISTINCT FROM OLD.team_id OR NEW.status IS DISTINCT FROM OLD.status) THEN
    RAISE EXCEPTION 'only an admin may change a user''s id, role, team or status'
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_users_guard BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION app_users_guard();

"""

# ---- policy expressions -------------------------------------------------------------------------

OWNED_READ = "owner_id = ANY (app_visible_owners())"
OWNED_WRITE = "app_can_write(owner_id)"
NULLABLE_READ = "(owner_id IS NULL AND app_actor_active()) OR owner_id = ANY (app_visible_owners())"
NULLABLE_WRITE = "(owner_id IS NULL AND app_actor_active() AND app_mode_ok()) OR app_can_write(owner_id)"
ACTIVE = "app_actor_active()"
ACTIVE_WRITE = "app_actor_active() AND app_mode_ok()"
ADMIN = "app_actor_role() = 'admin'"
ANY = "true"

# {table: (select, insert, update, delete)}; None = no policy for that command (the command is refused,
# because RLS is enabled and no policy permits it).
ORG_POLICIES = {
    "accounts": (ACTIVE, ACTIVE_WRITE, ACTIVE_WRITE, ACTIVE_WRITE),
    "people": (ACTIVE, ACTIVE_WRITE, ACTIVE_WRITE, ACTIVE_WRITE),
    "users": (ANY, f"{ADMIN} OR app_users_empty()", f"{ADMIN} OR id = app_actor_id()", ADMIN),
    "teams": (ANY, ADMIN, ADMIN, ADMIN),
    "team_managers": (ANY, ADMIN, ADMIN, ADMIN),
}
SYSTEM_POLICIES = {
    "wf_events": (ANY, ANY, ANY, ANY),
    "state": (ACTIVE, f"{ACTIVE_WRITE} AND ({ADMIN} OR current_setting('app.mode', true) = 'service')",
              f"{ACTIVE_WRITE} AND ({ADMIN} OR current_setting('app.mode', true) = 'service')",
              f"{ACTIVE_WRITE} AND ({ADMIN} OR current_setting('app.mode', true) = 'service')"),
    "user_state": ("user_id = app_actor_id() AND app_actor_active()",) * 4,
    "user_speaker_labels": ("user_id = app_actor_id() AND app_actor_active()",) * 4,
    "schema_migrations": (ANY, None, None, None),
}


def policies_for(table: str) -> tuple:
    """(select, insert, update, delete) expressions for a table, from its class."""
    kind = tenancy.TABLE_CLASS[table]
    if kind == tenancy.OWNED:
        if table in tenancy.OWNER_NULLABLE:
            return (NULLABLE_READ, NULLABLE_WRITE, NULLABLE_WRITE, NULLABLE_WRITE)
        return (OWNED_READ, OWNED_WRITE, OWNED_WRITE, OWNED_WRITE)
    table_policies = ORG_POLICIES if kind == tenancy.ORG else SYSTEM_POLICIES
    if table not in table_policies:
        raise KeyError(f"{table} is {kind} but store/rls.py has no policy set for it")
    return table_policies[table]


def table_block(table: str) -> str:
    kind = tenancy.TABLE_CLASS[table]
    select, insert, update, delete = policies_for(table)
    lines = [f"-- {table}: {kind}",
             f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;"]
    if kind == tenancy.OWNED:
        lines.append(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
    lines.append(f"CREATE POLICY {table}_select ON {table} FOR SELECT USING ({select});")
    if insert is not None:
        lines.append(f"CREATE POLICY {table}_insert ON {table} FOR INSERT WITH CHECK ({insert});")
    if update is not None:
        lines.append(f"CREATE POLICY {table}_update ON {table} FOR UPDATE USING ({update}) WITH CHECK ({update});")
    if delete is not None:
        lines.append(f"CREATE POLICY {table}_delete ON {table} FOR DELETE USING ({delete});")
    return "\n".join(lines) + "\n"


def generate() -> str:
    unknown = {t: k for t, k in tenancy.TABLE_CLASS.items() if k not in (tenancy.OWNED, tenancy.ORG, tenancy.SYSTEM)}
    if unknown:
        raise ValueError(f"unknown table classes: {unknown}")
    for table, policies in list(ORG_POLICIES.items()) + list(SYSTEM_POLICIES.items()):
        if tenancy.TABLE_CLASS.get(table) not in (tenancy.ORG, tenancy.SYSTEM):
            raise ValueError(f"store/rls.py names {table} which tenancy.py does not classify ORG or SYSTEM")
    parts = [HEADER, ROLE_BOOTSTRAP, FUNCTIONS]
    for kind, title in ((tenancy.OWNED, "OWNED: one rep's work; the owner writes, the owner's managers read"),
                        (tenancy.ORG, "ORG: the shared directory"),
                        (tenancy.SYSTEM, "SYSTEM: the machinery")):
        parts.append(f"-- ---- {title} " + "-" * max(4, 98 - len(title)) + "\n")
        for table in sorted(tenancy.tables_of(kind)):
            parts.append(table_block(table))
        parts.append("\n")
    return "".join(parts).rstrip() + "\n"
