#!/usr/bin/env python3
"""Generate a Postgres baseline from the tracked SQLite schema.

salescoach/store/pg/0001_baseline.sql was made by this script from the version-6 files and is
FROZEN: a Postgres database that applied it moves on only through the numbered migrations beside
it (0002_owner.sql, ...), each hand-written to land the shape the SQLite files declare at that
version (tests/test_schema_parity.py checks a migrated database against them). Running this script
today therefore prints the CURRENT schema to stdout for reading, or, with --write PATH, writes it
as the baseline of a fresh re-baseline (a new numbered file that replaces everything before it;
only ever done deliberately). `--check` fails when 0001 is not what the version-6 files produced,
which is a check nothing else needs any more and is kept for a re-baseline.

The SQLite files (store/schema-sales.sql + plugins/*.sql) stay the source of truth. This script
rewrites them for Postgres and nothing else:

  INTEGER PRIMARY KEY AUTOINCREMENT  ->  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  REAL -> DOUBLE PRECISION, BLOB -> BYTEA      (INTEGER and TEXT are the same words on both)
  PRAGMA lines dropped

CHECK constraints, defaults, UNIQUE, foreign keys, every index (partial ones included) and the
column order are kept verbatim, which is what tests/test_schema_parity.py verifies on a live
database. Run it after any schema change and commit the result; `--check` (CI) fails when the
committed file is not what the sources produce.

    python scripts/gen_pg_baseline.py [--write PATH]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from salescoach.store import catalog  # noqa: E402

OUT = ROOT / "salescoach" / "store" / "pg" / "0001_baseline.sql"

HEADER = """-- GENERATED by scripts/gen_pg_baseline.py from store/schema-sales.sql + plugins/*.sql. Do not edit:
-- change the SQLite files and regenerate. Postgres migration 0001: the whole schema at SQLite
-- user_version {version}. Later changes are numbered files beside this one (store/pgmigrate.py).
--
-- Timestamps are ISO-8601 TEXT, booleans are INTEGER 0/1 and JSON is TEXT decoded in Python, exactly
-- as on SQLite, so one query works on both backends (docs/architecture.md, "Two backends").

"""

_TYPES = {"REAL": "DOUBLE PRECISION", "BLOB": "BYTEA"}
_COLUMN = re.compile(r'^(\s+"?[A-Za-z_]\w*"?\s+)(INTEGER|TEXT|REAL|BLOB)\b(.*)$')


def convert(text: str) -> str:
    out = []
    for line in text.splitlines():
        if line.strip().upper().startswith("PRAGMA "):
            continue
        m = _COLUMN.match(line)
        if m:
            head, ctype, rest = m.groups()
            if ctype == "INTEGER" and re.match(r"\s*PRIMARY KEY AUTOINCREMENT\b", rest):
                rest = re.sub(r"^\s*PRIMARY KEY AUTOINCREMENT", " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", rest)
            line = f"{head}{_TYPES.get(ctype, ctype)}{rest}"
        out.append(line)
    return "\n".join(out).rstrip() + "\n"


def generate() -> str:
    from salescoach.store.stores import SCHEMA_VERSION
    parts = [HEADER.format(version=SCHEMA_VERSION)]
    for path in catalog.schema_files():
        parts.append(f"-- ==== {path.relative_to(ROOT)} ====\n")
        parts.append(convert(path.read_text()))
        parts.append("\n")
    return "".join(parts).rstrip() + "\n"


def main(argv) -> int:
    text = generate()
    if "--write" in argv:
        target = Path(argv[argv.index("--write") + 1])
        if target.resolve() == OUT.resolve():
            print(f"{OUT.relative_to(ROOT)} is frozen; write a new numbered baseline instead", file=sys.stderr)
            return 1
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
        print(f"wrote {target}")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
